sbt "run-main JackCompiler TestVM/Seven"
sbt "run-main JackCompiler TestVM/ConvertToBin"
sbt "run-main JackCompiler TestVM/Square"
sbt "run-main JackCompiler TestVM/Average"
sbt "run-main JackCompiler TestVM/Pong"
